cmake_minimum_required(VERSION 3.24)

if(DEFINED SYNTH_TEST_REPORTS)
    string(REPLACE "\\;" ";" SYNTH_TEST_REPORTS "${SYNTH_TEST_REPORTS}")
endif()

foreach(_required_variable IN ITEMS
        SYNTH_STAGE_ROOT
        SYNTH_STAGE_DIRECTORY
        SYNTH_STAGE_VST3_ARTIFACT
        SYNTH_STAGE_STANDALONE_ARTIFACT
        SYNTH_SOURCE_ROOT
        SYNTH_BUILD_ROOT)
    if(NOT DEFINED ${_required_variable} OR "${${_required_variable}}" STREQUAL "")
        message(FATAL_ERROR "${_required_variable} is required for development artifact staging")
    endif()
endforeach()

function(_synth_json_quote output_variable input_value)
    set(_escaped "${input_value}")
    string(REPLACE "\\" "\\\\" _escaped "${_escaped}")
    string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
    set(_hex_digits 0 1 2 3 4 5 6 7 8 9 a b c d e f)
    foreach(_control_code RANGE 1 31)
        string(ASCII ${_control_code} _control_character)
        math(EXPR _high_nibble "${_control_code} / 16")
        math(EXPR _low_nibble "${_control_code} % 16")
        list(GET _hex_digits ${_high_nibble} _high_digit)
        list(GET _hex_digits ${_low_nibble} _low_digit)
        set(_control_escape "\\u00${_high_digit}${_low_digit}")
        string(REPLACE "${_control_character}" "${_control_escape}" _escaped "${_escaped}")
    endforeach()
    set(${output_variable} "\"${_escaped}\"" PARENT_SCOPE)
endfunction()

function(_synth_json_set_string json_variable key value)
    _synth_json_quote(_quoted_value "${value}")
    string(JSON _updated_json SET "${${json_variable}}" "${key}" "${_quoted_value}")
    set(${json_variable} "${_updated_json}" PARENT_SCOPE)
endfunction()

function(_synth_normalize_manifest_path output_variable input_path)
    file(TO_CMAKE_PATH "${input_path}" _normalized_path)
    set(${output_variable} "${_normalized_path}" PARENT_SCOPE)
endfunction()

function(_synth_ensure_safe_stage_directory)
    cmake_path(ABSOLUTE_PATH SYNTH_STAGE_ROOT NORMALIZE OUTPUT_VARIABLE _stage_root)
    cmake_path(ABSOLUTE_PATH SYNTH_STAGE_DIRECTORY NORMALIZE OUTPUT_VARIABLE _stage_directory)
    cmake_path(ABSOLUTE_PATH SYNTH_SOURCE_ROOT NORMALIZE OUTPUT_VARIABLE _source_root)
    cmake_path(ABSOLUTE_PATH SYNTH_BUILD_ROOT NORMALIZE OUTPUT_VARIABLE _build_root)
    set(_synth_home_path "$ENV{HOME}")
    if(_synth_home_path STREQUAL "")
        set(_synth_home_path "$ENV{USERPROFILE}")
    endif()
    cmake_path(ABSOLUTE_PATH _synth_home_path NORMALIZE OUTPUT_VARIABLE _home_root)
    cmake_path(IS_PREFIX _stage_root "${_stage_directory}" NORMALIZE _stage_is_nested)
    get_filename_component(_stage_parent "${_stage_directory}" DIRECTORY)
    if(NOT _stage_is_nested OR _stage_root STREQUAL _stage_directory
       OR NOT _stage_parent STREQUAL _stage_root)
        message(FATAL_ERROR
            "SYNTH_STAGE_DIRECTORY must be a direct child of SYNTH_STAGE_ROOT; refusing cleanup of '${_stage_directory}'")
    endif()
    if(_stage_root STREQUAL "/"
       OR _stage_root MATCHES "^[A-Za-z]:/$"
       OR _stage_root STREQUAL _source_root
       OR (NOT _home_root STREQUAL "" AND _stage_root STREQUAL _home_root))
        message(FATAL_ERROR "SYNTH_STAGE_ROOT is too broad or collides with source/home: '${_stage_root}'")
    endif()
    if(_stage_directory STREQUAL _source_root
       OR _stage_directory STREQUAL _build_root
       OR (NOT _home_root STREQUAL "" AND _stage_directory STREQUAL _home_root))
        message(FATAL_ERROR "SYNTH_STAGE_DIRECTORY collides with a protected directory: '${_stage_directory}'")
    endif()
    set(SYNTH_STAGE_ROOT "${_stage_root}" PARENT_SCOPE)
    set(SYNTH_STAGE_DIRECTORY "${_stage_directory}" PARENT_SCOPE)
endfunction()

function(_synth_stage_product format source_artifact products_json_variable)
    if(NOT EXISTS "${source_artifact}")
        message(FATAL_ERROR "Generated ${format} artifact is missing: ${source_artifact}")
    endif()

    get_filename_component(_artifact_name "${source_artifact}" NAME)
    set(_product_directory "${SYNTH_STAGE_DIRECTORY}/${format}")
    set(_staged_product "${_product_directory}/${_artifact_name}")
    file(MAKE_DIRECTORY "${_product_directory}")
    if(IS_DIRECTORY "${source_artifact}")
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E copy_directory "${source_artifact}" "${_staged_product}"
            RESULT_VARIABLE _copy_status)
    else()
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${source_artifact}" "${_staged_product}"
            RESULT_VARIABLE _copy_status)
    endif()
    if(_copy_status)
        message(FATAL_ERROR "Could not stage ${format} artifact: ${source_artifact}")
    endif()

    if(IS_DIRECTORY "${_staged_product}")
        file(GLOB_RECURSE _payload_files LIST_DIRECTORIES FALSE
            RELATIVE "${_staged_product}" "${_staged_product}/*")
        set(_payload_root "${_staged_product}")
        file(RELATIVE_PATH _payload_root_relative_path "${SYNTH_STAGE_DIRECTORY}" "${_staged_product}")
    else()
        set(_payload_files "${_artifact_name}")
        set(_payload_root "${_product_directory}")
        file(RELATIVE_PATH _payload_root_relative_path "${SYNTH_STAGE_DIRECTORY}" "${_product_directory}")
    endif()
    list(SORT _payload_files)
    if(NOT _payload_files)
        message(FATAL_ERROR "Staged ${format} artifact contains no payload files")
    endif()

    set(_files_json "[]")
    set(_aggregate_input "")
    set(_file_index 0)
    foreach(_payload_relative_path IN LISTS _payload_files)
        if(IS_DIRECTORY "${_payload_root}/${_payload_relative_path}")
            continue()
        endif()
        file(SHA256 "${_payload_root}/${_payload_relative_path}" _payload_sha256)
        _synth_normalize_manifest_path(_payload_relative_path "${_payload_relative_path}")
        set(_file_json "{}")
        _synth_json_set_string(_file_json path "${_payload_relative_path}")
        _synth_json_set_string(_file_json sha256 "${_payload_sha256}")
        string(JSON _files_json SET "${_files_json}" ${_file_index} "${_file_json}")
        string(APPEND _aggregate_input "${_payload_sha256}  ${_payload_relative_path}\n")
        math(EXPR _file_index "${_file_index} + 1")
    endforeach()
    if(_file_index EQUAL 0)
        message(FATAL_ERROR "Staged ${format} artifact contains no hashable payload files")
    endif()
    string(SHA256 _aggregate_sha256 "${_aggregate_input}")

    file(RELATIVE_PATH _product_relative_path "${SYNTH_STAGE_DIRECTORY}" "${_staged_product}")
    _synth_normalize_manifest_path(_product_relative_path "${_product_relative_path}")
    _synth_normalize_manifest_path(_payload_root_relative_path "${_payload_root_relative_path}")
    set(_product_json "{}")
    _synth_json_set_string(_product_json format "${format}")
    _synth_json_set_string(_product_json relative_path "${_product_relative_path}")
    _synth_json_set_string(_product_json payload_root_relative_path "${_payload_root_relative_path}")
    _synth_json_set_string(_product_json aggregate_sha256 "${_aggregate_sha256}")
    string(JSON _product_json SET "${_product_json}" files "${_files_json}")

    string(JSON _product_count LENGTH "${${products_json_variable}}")
    string(JSON _updated_products SET "${${products_json_variable}}" ${_product_count} "${_product_json}")
    set(${products_json_variable} "${_updated_products}" PARENT_SCOPE)
endfunction()

_synth_ensure_safe_stage_directory()
set(_stage_marker_name ".synth-development-stage-marker")
set(_stage_marker_contents "ModelD development staging v1\n")
if(EXISTS "${SYNTH_STAGE_DIRECTORY}")
    set(_stage_marker_path "${SYNTH_STAGE_DIRECTORY}/${_stage_marker_name}")
    if(NOT EXISTS "${_stage_marker_path}")
        message(FATAL_ERROR
            "Refusing to clean pre-existing stage directory without project marker: ${SYNTH_STAGE_DIRECTORY}")
    endif()
    file(READ "${_stage_marker_path}" _existing_stage_marker)
    if(NOT _existing_stage_marker STREQUAL _stage_marker_contents)
        message(FATAL_ERROR
            "Refusing to clean stage directory with an unrecognized project marker: ${SYNTH_STAGE_DIRECTORY}")
    endif()
endif()
file(REMOVE_RECURSE "${SYNTH_STAGE_DIRECTORY}")
file(MAKE_DIRECTORY "${SYNTH_STAGE_DIRECTORY}")
file(WRITE "${SYNTH_STAGE_DIRECTORY}/${_stage_marker_name}" "${_stage_marker_contents}")

execute_process(
    COMMAND git -C "${SYNTH_SOURCE_ROOT}" rev-parse HEAD
    RESULT_VARIABLE _source_git_status
    OUTPUT_VARIABLE _source_git_commit
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE)
if(_source_git_status)
    set(_source_git_commit "unknown")
endif()
execute_process(
    COMMAND git -C "${SYNTH_SOURCE_ROOT}" status --porcelain
    RESULT_VARIABLE _source_dirty_status
    OUTPUT_VARIABLE _source_dirty_output
    ERROR_QUIET
    OUTPUT_STRIP_TRAILING_WHITESPACE)
if(_source_dirty_status OR _source_dirty_output)
    set(_source_git_dirty true)
else()
    set(_source_git_dirty false)
endif()

set(_products_json "[]")
_synth_stage_product("VST3" "${SYNTH_STAGE_VST3_ARTIFACT}" _products_json)
_synth_stage_product("Standalone" "${SYNTH_STAGE_STANDALONE_ARTIFACT}" _products_json)
if(DEFINED SYNTH_STAGE_AU_ARTIFACT AND NOT "${SYNTH_STAGE_AU_ARTIFACT}" STREQUAL "")
    _synth_stage_product("AU" "${SYNTH_STAGE_AU_ARTIFACT}" _products_json)
endif()

set(_formats_json "[]")
set(_format_index 0)
foreach(_format IN ITEMS VST3 Standalone)
    _synth_json_quote(_format_json "${_format}")
    string(JSON _formats_json SET "${_formats_json}" ${_format_index} "${_format_json}")
    math(EXPR _format_index "${_format_index} + 1")
endforeach()
if(DEFINED SYNTH_STAGE_AU_ARTIFACT AND NOT "${SYNTH_STAGE_AU_ARTIFACT}" STREQUAL "")
    _synth_json_quote(_format_json "AU")
    string(JSON _formats_json SET "${_formats_json}" ${_format_index} "${_format_json}")
endif()

set(_reports_json "[]")
set(_report_index 0)
set(_report_paths "")
if(DEFINED SYNTH_TEST_REPORTS AND NOT "${SYNTH_TEST_REPORTS}" STREQUAL "")
    file(REAL_PATH "${SYNTH_BUILD_ROOT}" _build_root)
    foreach(_report IN LISTS SYNTH_TEST_REPORTS)
        if(NOT EXISTS "${_report}")
            message(FATAL_ERROR "Declared test report is missing: ${_report}")
        endif()
        file(REAL_PATH "${_report}" _report_real_path)
        file(RELATIVE_PATH _report_relative_path "${_build_root}" "${_report_real_path}")
        _synth_normalize_manifest_path(_report_relative_path "${_report_relative_path}")
        if(_report_relative_path MATCHES "(^|/)[.][.](/|$)" OR IS_ABSOLUTE "${_report_relative_path}")
            message(FATAL_ERROR "Declared test report must be under SYNTH_BUILD_ROOT: ${_report}")
        endif()
        list(FIND _report_paths "${_report_relative_path}" _duplicate_report)
        if(NOT _duplicate_report EQUAL -1)
            message(FATAL_ERROR "Declared test report is duplicated: ${_report_relative_path}")
        endif()
        list(APPEND _report_paths "${_report_relative_path}")
    endforeach()
    list(SORT _report_paths)
    foreach(_report_relative_path IN LISTS _report_paths)
        file(SHA256 "${_build_root}/${_report_relative_path}" _report_sha256)
        set(_report_json "{}")
        _synth_json_set_string(_report_json path "${_report_relative_path}")
        _synth_json_set_string(_report_json sha256 "${_report_sha256}")
        string(JSON _reports_json SET "${_reports_json}" ${_report_index} "${_report_json}")
        math(EXPR _report_index "${_report_index} + 1")
    endforeach()
endif()

if(SYNTH_IDENTITY_APPROVED)
    set(_identity_approved_json true)
    set(_distribution_eligible_json false)
else()
    set(_identity_approved_json false)
    set(_distribution_eligible_json false)
endif()

set(_manifest "{}")
string(JSON _manifest SET "${_manifest}" schema_version 1)
_synth_json_set_string(_manifest project_version "${SYNTH_PROJECT_VERSION}")
set(_source_json "{}")
_synth_json_set_string(_source_json git_commit "${_source_git_commit}")
string(JSON _source_json SET "${_source_json}" dirty "${_source_git_dirty}")
string(JSON _manifest SET "${_manifest}" source "${_source_json}")
set(_juce_json "{}")
_synth_json_set_string(_juce_json required_commit "${SYNTH_REQUIRED_JUCE_COMMIT}")
_synth_json_set_string(_juce_json resolved_commit "${SYNTH_RESOLVED_JUCE_COMMIT}")
string(JSON _manifest SET "${_manifest}" juce "${_juce_json}")
set(_build_json "{}")
_synth_json_set_string(_build_json compiler_id "${SYNTH_COMPILER_ID}")
_synth_json_set_string(_build_json compiler_version "${SYNTH_COMPILER_VERSION}")
_synth_json_set_string(_build_json sdk_identifier "${SYNTH_SDK_IDENTIFIER}")
_synth_json_set_string(_build_json sdk_version "${SYNTH_SDK_VERSION}")
_synth_json_set_string(_build_json configuration "${SYNTH_CONFIGURATION}")
_synth_json_set_string(_build_json os "${SYNTH_SYSTEM_NAME}")
_synth_json_set_string(_build_json architecture "${SYNTH_ARCHITECTURE}")
string(JSON _manifest SET "${_manifest}" build "${_build_json}")
string(JSON _manifest SET "${_manifest}" enabled_formats "${_formats_json}")
set(_identity_json "{}")
_synth_json_set_string(_identity_json product_name "${SYNTH_PRODUCT_NAME}")
_synth_json_set_string(_identity_json manufacturer_name "${SYNTH_MANUFACTURER_NAME}")
_synth_json_set_string(_identity_json manufacturer_domain "${SYNTH_MANUFACTURER_DOMAIN}")
_synth_json_set_string(_identity_json bundle_id "${SYNTH_BUNDLE_ID}")
_synth_json_set_string(_identity_json manufacturer_code "${SYNTH_MANUFACTURER_CODE}")
_synth_json_set_string(_identity_json product_code "${SYNTH_PRODUCT_CODE}")
string(JSON _identity_json SET "${_identity_json}" identity_approved "${_identity_approved_json}")
string(JSON _identity_json SET "${_identity_json}" distribution_eligible "${_distribution_eligible_json}")
string(JSON _manifest SET "${_manifest}" identity "${_identity_json}")
string(JSON _manifest SET "${_manifest}" products "${_products_json}")
string(JSON _manifest SET "${_manifest}" test_reports "${_reports_json}")

file(WRITE "${SYNTH_STAGE_DIRECTORY}/build-manifest.json" "${_manifest}\n")
