cmake_minimum_required(VERSION 3.24)

foreach(_required_variable IN ITEMS SYNTH_STAGE_DIRECTORY SYNTH_BUILD_ROOT SYNTH_EXPECTED_FORMATS)
    if(NOT DEFINED ${_required_variable} OR "${${_required_variable}}" STREQUAL "")
        message(FATAL_ERROR "${_required_variable} is required for staged artifact verification")
    endif()
endforeach()
string(REPLACE "\\;" ";" SYNTH_EXPECTED_FORMATS "${SYNTH_EXPECTED_FORMATS}")

function(_synth_normalize_relative_path output_variable input_path)
    string(REPLACE "\\" "/" _separator_normalized_path "${input_path}")
    file(TO_CMAKE_PATH "${_separator_normalized_path}" _normalized_path)
    if(_normalized_path STREQUAL ""
       OR _normalized_path MATCHES "^/"
       OR _normalized_path MATCHES "^[A-Za-z]:"
       OR _normalized_path MATCHES "(^|/)[.][.](/|$)")
        message(FATAL_ERROR "Manifest contains an unsafe relative path: ${input_path}")
    endif()
    cmake_path(NORMAL_PATH _normalized_path OUTPUT_VARIABLE _canonical_relative_path)
    set(${output_variable} "${_canonical_relative_path}" PARENT_SCOPE)
endfunction()

function(_synth_existing_path_within_root output_variable root_directory relative_path description)
    _synth_normalize_relative_path(_normalized_relative_path "${relative_path}")
    file(REAL_PATH "${root_directory}" _root_real_path)
    set(_candidate_path "${_root_real_path}/${_normalized_relative_path}")
    if(NOT EXISTS "${_candidate_path}")
        message(FATAL_ERROR "${description} is missing: ${_normalized_relative_path}")
    endif()
    file(REAL_PATH "${_candidate_path}" _candidate_real_path)
    file(RELATIVE_PATH _candidate_from_root "${_root_real_path}" "${_candidate_real_path}")
    file(TO_CMAKE_PATH "${_candidate_from_root}" _candidate_from_root)
    if(_candidate_from_root STREQUAL ""
       OR _candidate_from_root MATCHES "^/"
       OR _candidate_from_root MATCHES "^[A-Za-z]:"
       OR _candidate_from_root MATCHES "(^|/)[.][.](/|$)")
        message(FATAL_ERROR "${description} escapes its trusted root: ${_normalized_relative_path}")
    endif()
    set(${output_variable} "${_candidate_real_path}" PARENT_SCOPE)
endfunction()

function(_synth_require_exact_format_set subject actual_formats)
    set(_actual_formats ${actual_formats})
    set(_seen_formats "")
    foreach(_format IN LISTS _actual_formats)
        list(FIND SYNTH_EXPECTED_FORMATS "${_format}" _expected_index)
        if(_expected_index EQUAL -1)
            message(FATAL_ERROR "${subject} declares unexpected format: ${_format}")
        endif()
        list(FIND _seen_formats "${_format}" _duplicate_index)
        if(NOT _duplicate_index EQUAL -1)
            message(FATAL_ERROR "${subject} declares duplicate format: ${_format}")
        endif()
        list(APPEND _seen_formats "${_format}")
    endforeach()
    list(LENGTH _seen_formats _seen_count)
    list(LENGTH SYNTH_EXPECTED_FORMATS _expected_count)
    if(NOT _seen_count EQUAL _expected_count)
        message(FATAL_ERROR "${subject} does not declare every expected format")
    endif()
    foreach(_expected_format IN LISTS SYNTH_EXPECTED_FORMATS)
        list(FIND _seen_formats "${_expected_format}" _present_index)
        if(_present_index EQUAL -1)
            message(FATAL_ERROR "${subject} is missing expected format: ${_expected_format}")
        endif()
    endforeach()
endfunction()

file(REAL_PATH "${SYNTH_STAGE_DIRECTORY}" _stage_root)
file(REAL_PATH "${SYNTH_BUILD_ROOT}" _build_root)
set(_manifest_path "${_stage_root}/build-manifest.json")
if(NOT EXISTS "${_manifest_path}")
    message(FATAL_ERROR "Staged artifact manifest is missing: ${_manifest_path}")
endif()
file(READ "${_manifest_path}" _manifest)
string(JSON _manifest_type ERROR_VARIABLE _json_error TYPE "${_manifest}")
if(_json_error OR NOT _manifest_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Staged artifact manifest is not valid JSON: ${_json_error}")
endif()
string(JSON _schema_version GET "${_manifest}" schema_version)
if(NOT _schema_version STREQUAL "1")
    message(FATAL_ERROR "Unsupported staged artifact manifest schema: ${_schema_version}")
endif()

string(JSON _identity_approved GET "${_manifest}" identity identity_approved)
string(JSON _distribution_eligible GET "${_manifest}" identity distribution_eligible)
string(JSON _manufacturer_name GET "${_manifest}" identity manufacturer_name)
string(JSON _manufacturer_domain GET "${_manifest}" identity manufacturer_domain)
if(_distribution_eligible)
    message(FATAL_ERROR "Development staging manifest must remain non-distributable")
endif()
if((_manufacturer_name STREQUAL "" OR _manufacturer_name STREQUAL "yourcompany"
    OR _manufacturer_domain STREQUAL "" OR _manufacturer_domain MATCHES "(^|\\.)yourcompany($|\\.)"
    OR _manufacturer_domain MATCHES "(^|\\.)example\\.(com|net|org)$")
   AND _identity_approved)
    message(FATAL_ERROR "Placeholder identity cannot be recorded as approved")
endif()

string(JSON _enabled_format_count LENGTH "${_manifest}" enabled_formats)
set(_enabled_formats "")
if(_enabled_format_count GREATER 0)
    math(EXPR _last_enabled_format_index "${_enabled_format_count} - 1")
    foreach(_format_index RANGE 0 ${_last_enabled_format_index})
        string(JSON _enabled_format GET "${_manifest}" enabled_formats ${_format_index})
        list(APPEND _enabled_formats "${_enabled_format}")
    endforeach()
endif()
_synth_require_exact_format_set("enabled_formats" "${_enabled_formats}")

set(_declared_payload_paths "")
set(_declared_product_paths "")
set(_product_formats "")
string(JSON _product_count LENGTH "${_manifest}" products)
if(_product_count LESS 1)
    message(FATAL_ERROR "Staged artifact manifest declares no products")
endif()
math(EXPR _last_product_index "${_product_count} - 1")
foreach(_product_index RANGE 0 ${_last_product_index})
    string(JSON _product GET "${_manifest}" products ${_product_index})
    string(JSON _format GET "${_product}" format)
    list(FIND SYNTH_EXPECTED_FORMATS "${_format}" _format_expected_index)
    if(_format_expected_index EQUAL -1)
        message(FATAL_ERROR "Product declares unexpected format: ${_format}")
    endif()
    list(FIND _product_formats "${_format}" _duplicate_format_index)
    if(NOT _duplicate_format_index EQUAL -1)
        message(FATAL_ERROR "Manifest declares duplicate product format: ${_format}")
    endif()
    list(APPEND _product_formats "${_format}")

    string(JSON _product_relative_path GET "${_product}" relative_path)
    string(JSON _payload_root_relative_path GET "${_product}" payload_root_relative_path)
    _synth_normalize_relative_path(_product_relative_path "${_product_relative_path}")
    _synth_normalize_relative_path(_payload_root_relative_path "${_payload_root_relative_path}")
    if(NOT _product_relative_path MATCHES "^${_format}/[^/]+$")
        message(FATAL_ERROR "Product path does not match its trusted format: ${_product_relative_path}")
    endif()
    list(FIND _declared_product_paths "${_product_relative_path}" _duplicate_product)
    if(NOT _duplicate_product EQUAL -1)
        message(FATAL_ERROR "Manifest declares a duplicate product: ${_product_relative_path}")
    endif()
    list(APPEND _declared_product_paths "${_product_relative_path}")
    _synth_existing_path_within_root(_product_path "${_stage_root}" "${_product_relative_path}" "Declared staged product")
    _synth_existing_path_within_root(_payload_root_path "${_stage_root}" "${_payload_root_relative_path}" "Declared product payload root")

    if(IS_DIRECTORY "${_product_path}")
        if(NOT _payload_root_relative_path STREQUAL _product_relative_path)
            message(FATAL_ERROR "Bundle payload root must equal its product path: ${_product_relative_path}")
        endif()
    else()
        get_filename_component(_product_parent_relative_path "${_product_relative_path}" DIRECTORY)
        get_filename_component(_product_name "${_product_relative_path}" NAME)
        if(NOT _payload_root_relative_path STREQUAL _product_parent_relative_path)
            message(FATAL_ERROR "Single-file payload root must be its product parent: ${_product_relative_path}")
        endif()
    endif()

    string(JSON _file_count LENGTH "${_product}" files)
    if(_file_count LESS 1)
        message(FATAL_ERROR "Manifest product has no payload inventory: ${_product_relative_path}")
    endif()
    if(NOT IS_DIRECTORY "${_product_path}" AND NOT _file_count EQUAL 1)
        message(FATAL_ERROR "Single-file product must have exactly one payload entry: ${_product_relative_path}")
    endif()
    set(_aggregate_input "")
    math(EXPR _last_file_index "${_file_count} - 1")
    foreach(_file_index RANGE 0 ${_last_file_index})
        string(JSON _entry GET "${_product}" files ${_file_index})
        string(JSON _payload_relative_path GET "${_entry}" path)
        string(JSON _declared_sha256 GET "${_entry}" sha256)
        _synth_normalize_relative_path(_payload_relative_path "${_payload_relative_path}")
        if(NOT IS_DIRECTORY "${_product_path}" AND NOT _payload_relative_path STREQUAL _product_name)
            message(FATAL_ERROR "Single-file product inventory does not name its product: ${_product_relative_path}")
        endif()
        set(_combined_relative_path "${_payload_root_relative_path}/${_payload_relative_path}")
        _synth_normalize_relative_path(_combined_relative_path "${_combined_relative_path}")
        list(FIND _declared_payload_paths "${_combined_relative_path}" _duplicate_payload)
        if(NOT _duplicate_payload EQUAL -1)
            message(FATAL_ERROR "Manifest declares a duplicate payload: ${_combined_relative_path}")
        endif()
        list(APPEND _declared_payload_paths "${_combined_relative_path}")
        _synth_existing_path_within_root(_payload_path "${_stage_root}" "${_combined_relative_path}" "Declared staged payload")
        if(IS_DIRECTORY "${_payload_path}")
            message(FATAL_ERROR "Declared staged payload is a directory: ${_combined_relative_path}")
        endif()
        file(SHA256 "${_payload_path}" _actual_sha256)
        if(NOT _actual_sha256 STREQUAL _declared_sha256)
            message(FATAL_ERROR "Staged payload hash mismatch: ${_combined_relative_path}")
        endif()
        string(APPEND _aggregate_input "${_declared_sha256}  ${_payload_relative_path}\n")
    endforeach()
    string(SHA256 _actual_aggregate_sha256 "${_aggregate_input}")
    string(JSON _declared_aggregate_sha256 GET "${_product}" aggregate_sha256)
    if(NOT _actual_aggregate_sha256 STREQUAL _declared_aggregate_sha256)
        message(FATAL_ERROR "Staged product aggregate hash mismatch: ${_product_relative_path}")
    endif()
endforeach()
_synth_require_exact_format_set("products" "${_product_formats}")

file(GLOB_RECURSE _actual_payload_paths LIST_DIRECTORIES FALSE
    RELATIVE "${_stage_root}" "${_stage_root}/*")
foreach(_actual_relative_path IN LISTS _actual_payload_paths)
    _synth_normalize_relative_path(_actual_relative_path "${_actual_relative_path}")
    if(_actual_relative_path STREQUAL "build-manifest.json"
       OR _actual_relative_path STREQUAL ".synth-development-stage-marker")
        continue()
    endif()
    if(_actual_relative_path STREQUAL "validation-manifest.json")
        if(DEFINED SYNTH_ALLOW_VALIDATION_MANIFEST
           AND SYNTH_ALLOW_VALIDATION_MANIFEST)
            continue()
        endif()
        message(FATAL_ERROR
            "Validation metadata is present but explicit linked-manifest verification was not enabled")
    endif()
    list(FIND _declared_payload_paths "${_actual_relative_path}" _declared_payload)
    if(_declared_payload EQUAL -1)
        message(FATAL_ERROR "Undeclared staged payload is present: ${_actual_relative_path}")
    endif()
endforeach()

set(_declared_report_paths "")
string(JSON _report_count LENGTH "${_manifest}" test_reports)
if(_report_count GREATER 0)
    math(EXPR _last_report_index "${_report_count} - 1")
    foreach(_report_index RANGE 0 ${_last_report_index})
        string(JSON _report GET "${_manifest}" test_reports ${_report_index})
        string(JSON _report_relative_path GET "${_report}" path)
        string(JSON _declared_sha256 GET "${_report}" sha256)
        _synth_normalize_relative_path(_report_relative_path "${_report_relative_path}")
        list(FIND _declared_report_paths "${_report_relative_path}" _duplicate_report)
        if(NOT _duplicate_report EQUAL -1)
            message(FATAL_ERROR "Manifest declares a duplicate test report: ${_report_relative_path}")
        endif()
        list(APPEND _declared_report_paths "${_report_relative_path}")
        _synth_existing_path_within_root(_report_path "${_build_root}" "${_report_relative_path}" "Declared test report")
        if(IS_DIRECTORY "${_report_path}")
            message(FATAL_ERROR "Declared test report is a directory: ${_report_relative_path}")
        endif()
        file(SHA256 "${_report_path}" _actual_sha256)
        if(NOT _actual_sha256 STREQUAL _declared_sha256)
            message(FATAL_ERROR "Declared test report hash mismatch: ${_report_relative_path}")
        endif()
    endforeach()
endif()
