cmake_minimum_required(VERSION 3.24)

foreach(_required_variable IN ITEMS SYNTH_STAGE_DIRECTORY SYNTH_BUILD_ROOT)
    if(NOT DEFINED ${_required_variable} OR "${${_required_variable}}" STREQUAL "")
        message(FATAL_ERROR "${_required_variable} is required for staged artifact verification")
    endif()
endforeach()

function(_synth_manifest_path_is_safe input_path)
    if("${input_path}" STREQUAL ""
       OR "${input_path}" MATCHES "^/"
       OR "${input_path}" MATCHES "^[A-Za-z]:/"
       OR "${input_path}" MATCHES "(^|/)[.][.](/|$)")
        message(FATAL_ERROR "Manifest contains an unsafe relative path: ${input_path}")
    endif()
endfunction()

function(_synth_normalize_manifest_path output_variable input_path)
    file(TO_CMAKE_PATH "${input_path}" _normalized_path)
    set(${output_variable} "${_normalized_path}" PARENT_SCOPE)
endfunction()

set(_manifest_path "${SYNTH_STAGE_DIRECTORY}/build-manifest.json")
if(NOT EXISTS "${_manifest_path}")
    message(FATAL_ERROR "Staged artifact manifest is missing: ${_manifest_path}")
endif()
file(READ "${_manifest_path}" _manifest)
string(JSON _manifest_type ERROR_VARIABLE _json_error TYPE "${_manifest}")
if(_json_error OR NOT _manifest_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Staged artifact manifest is not valid JSON: ${_json_error}")
endif()
string(JSON _schema_version GET "${_manifest}" schema_version)
if(NOT _schema_version STREQUAL "1")
    message(FATAL_ERROR "Unsupported staged artifact manifest schema: ${_schema_version}")
endif()
string(JSON _identity_approved GET "${_manifest}" identity identity_approved)
string(JSON _distribution_eligible GET "${_manifest}" identity distribution_eligible)
string(JSON _manufacturer_name GET "${_manifest}" identity manufacturer_name)
string(JSON _manufacturer_domain GET "${_manifest}" identity manufacturer_domain)
if(_distribution_eligible)
    message(FATAL_ERROR "Development staging manifest must remain non-distributable")
endif()
if((_manufacturer_name STREQUAL "" OR _manufacturer_name STREQUAL "yourcompany"
    OR _manufacturer_domain STREQUAL "" OR _manufacturer_domain MATCHES "(^|\\.)yourcompany($|\\.)"
    OR _manufacturer_domain MATCHES "(^|\\.)example\\.(com|net|org)$")
   AND _identity_approved)
    message(FATAL_ERROR "Placeholder identity cannot be recorded as approved")
endif()

set(_declared_payload_paths "")
set(_declared_product_paths "")
string(JSON _product_count LENGTH "${_manifest}" products)
if(_product_count LESS 1)
    message(FATAL_ERROR "Staged artifact manifest declares no products")
endif()
math(EXPR _last_product_index "${_product_count} - 1")
foreach(_product_index RANGE 0 ${_last_product_index})
    string(JSON _product GET "${_manifest}" products ${_product_index})
    string(JSON _product_relative_path GET "${_product}" relative_path)
    string(JSON _payload_root_relative_path GET "${_product}" payload_root_relative_path)
    _synth_manifest_path_is_safe("${_product_relative_path}")
    _synth_manifest_path_is_safe("${_payload_root_relative_path}")
    list(FIND _declared_product_paths "${_product_relative_path}" _duplicate_product)
    if(NOT _duplicate_product EQUAL -1)
        message(FATAL_ERROR "Manifest declares a duplicate product: ${_product_relative_path}")
    endif()
    list(APPEND _declared_product_paths "${_product_relative_path}")
    if(NOT EXISTS "${SYNTH_STAGE_DIRECTORY}/${_product_relative_path}")
        message(FATAL_ERROR "Declared staged product is missing: ${_product_relative_path}")
    endif()
    string(JSON _file_count LENGTH "${_product}" files)
    if(_file_count LESS 1)
        message(FATAL_ERROR "Manifest product has no payload inventory: ${_product_relative_path}")
    endif()
    set(_aggregate_input "")
    math(EXPR _last_file_index "${_file_count} - 1")
    foreach(_file_index RANGE 0 ${_last_file_index})
        string(JSON _entry GET "${_product}" files ${_file_index})
        string(JSON _payload_relative_path GET "${_entry}" path)
        string(JSON _declared_sha256 GET "${_entry}" sha256)
        _synth_manifest_path_is_safe("${_payload_relative_path}")
        set(_combined_relative_path "${_payload_root_relative_path}/${_payload_relative_path}")
        _synth_normalize_manifest_path(_combined_relative_path "${_combined_relative_path}")
        list(FIND _declared_payload_paths "${_combined_relative_path}" _duplicate_payload)
        if(NOT _duplicate_payload EQUAL -1)
            message(FATAL_ERROR "Manifest declares a duplicate payload: ${_combined_relative_path}")
        endif()
        list(APPEND _declared_payload_paths "${_combined_relative_path}")
        set(_payload_path "${SYNTH_STAGE_DIRECTORY}/${_combined_relative_path}")
        if(NOT EXISTS "${_payload_path}" OR IS_DIRECTORY "${_payload_path}")
            message(FATAL_ERROR "Declared staged payload is missing: ${_combined_relative_path}")
        endif()
        file(SHA256 "${_payload_path}" _actual_sha256)
        if(NOT _actual_sha256 STREQUAL _declared_sha256)
            message(FATAL_ERROR "Staged payload hash mismatch: ${_combined_relative_path}")
        endif()
        string(APPEND _aggregate_input "${_declared_sha256}  ${_payload_relative_path}\n")
    endforeach()
    string(SHA256 _actual_aggregate_sha256 "${_aggregate_input}")
    string(JSON _declared_aggregate_sha256 GET "${_product}" aggregate_sha256)
    if(NOT _actual_aggregate_sha256 STREQUAL _declared_aggregate_sha256)
        message(FATAL_ERROR "Staged product aggregate hash mismatch: ${_product_relative_path}")
    endif()
endforeach()

file(GLOB_RECURSE _actual_payload_paths LIST_DIRECTORIES FALSE
    RELATIVE "${SYNTH_STAGE_DIRECTORY}" "${SYNTH_STAGE_DIRECTORY}/*")
foreach(_actual_relative_path IN LISTS _actual_payload_paths)
    _synth_normalize_manifest_path(_actual_relative_path "${_actual_relative_path}")
    if(_actual_relative_path STREQUAL "build-manifest.json"
       OR _actual_relative_path STREQUAL ".synth-development-stage-marker")
        continue()
    endif()
    list(FIND _declared_payload_paths "${_actual_relative_path}" _declared_payload)
    if(_declared_payload EQUAL -1)
        message(FATAL_ERROR "Undeclared staged payload is present: ${_actual_relative_path}")
    endif()
endforeach()

set(_declared_report_paths "")
string(JSON _report_count LENGTH "${_manifest}" test_reports)
if(_report_count GREATER 0)
    math(EXPR _last_report_index "${_report_count} - 1")
    foreach(_report_index RANGE 0 ${_last_report_index})
        string(JSON _report GET "${_manifest}" test_reports ${_report_index})
        string(JSON _report_relative_path GET "${_report}" path)
        string(JSON _declared_sha256 GET "${_report}" sha256)
        _synth_manifest_path_is_safe("${_report_relative_path}")
        list(FIND _declared_report_paths "${_report_relative_path}" _duplicate_report)
        if(NOT _duplicate_report EQUAL -1)
            message(FATAL_ERROR "Manifest declares a duplicate test report: ${_report_relative_path}")
        endif()
        list(APPEND _declared_report_paths "${_report_relative_path}")
        set(_report_path "${SYNTH_BUILD_ROOT}/${_report_relative_path}")
        if(NOT EXISTS "${_report_path}" OR IS_DIRECTORY "${_report_path}")
            message(FATAL_ERROR "Declared test report is missing: ${_report_relative_path}")
        endif()
        file(SHA256 "${_report_path}" _actual_sha256)
        if(NOT _actual_sha256 STREQUAL _declared_sha256)
            message(FATAL_ERROR "Declared test report hash mismatch: ${_report_relative_path}")
        endif()
    endforeach()
endif()
