cmake_minimum_required(VERSION 3.24)

foreach(_required_variable IN ITEMS
        SYNTH_BUILD_ROOT
        SYNTH_STAGE_DIRECTORY
        SYNTH_HOST_MATRIX_PATH
        SYNTH_REPEAT_COUNT
        SYNTH_SEED
        SYNTH_PRODUCT_CODE
        SYNTH_MANUFACTURER_CODE
        SYNTH_PROJECT_VERSION
        SYNTH_EXPECTED_EVIDENCE)
    if(NOT DEFINED ${_required_variable} OR "${${_required_variable}}" STREQUAL "")
        message(FATAL_ERROR "${_required_variable} is required to verify validation metadata")
    endif()
endforeach()
string(REPLACE "\\;" ";" SYNTH_EXPECTED_EVIDENCE "${SYNTH_EXPECTED_EVIDENCE}")

function(_synth_read_json output_variable path description)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "${description} is missing: ${path}")
    endif()
    file(READ "${path}" _json)
    string(JSON _type ERROR_VARIABLE _error TYPE "${_json}")
    if(_error OR NOT _type STREQUAL "OBJECT")
        message(FATAL_ERROR "${description} is invalid JSON: ${_error}")
    endif()
    set(${output_variable} "${_json}" PARENT_SCOPE)
endfunction()

function(_synth_require_status status context)
    if(NOT status MATCHES "^(not-run|in-progress|blocked|fail|pass)$")
        message(FATAL_ERROR "${context} has an unsupported status token: ${status}")
    endif()
endfunction()

function(_synth_require_same_json left_json right_json context)
    string(JSON _left_normalized SET "{}" value "${left_json}")
    string(JSON _right_normalized SET "{}" value "${right_json}")
    if(NOT _left_normalized STREQUAL _right_normalized)
        message(FATAL_ERROR "${context} differs from its hashed evidence report")
    endif()
endfunction()

function(_synth_verify_build_evidence relative_path declared_sha256 description)
    string(REPLACE "\\" "/" _relative_path "${relative_path}")
    if(_relative_path STREQUAL ""
       OR IS_ABSOLUTE "${_relative_path}"
       OR _relative_path MATCHES "^[A-Za-z]:"
       OR _relative_path MATCHES "(^|/)[.][.](/|$)")
        message(FATAL_ERROR "${description} has an unsafe path: ${relative_path}")
    endif()
    if(NOT EXISTS "${_build_root}/${_relative_path}")
        message(FATAL_ERROR "${description} is missing: ${_relative_path}")
    endif()
    file(REAL_PATH "${_build_root}/${_relative_path}" _evidence_real)
    file(RELATIVE_PATH _from_build "${_build_root}" "${_evidence_real}")
    string(REPLACE "\\" "/" _from_build "${_from_build}")
    if(IS_ABSOLUTE "${_from_build}" OR _from_build MATCHES "(^|/)[.][.](/|$)")
        message(FATAL_ERROR "${description} escapes the build root: ${relative_path}")
    endif()
    if(IS_DIRECTORY "${_evidence_real}")
        message(FATAL_ERROR "${description} is a directory: ${relative_path}")
    endif()
    file(SHA256 "${_evidence_real}" _actual_sha256)
    if(NOT _actual_sha256 STREQUAL declared_sha256)
        message(FATAL_ERROR "${description} hash mismatch: ${relative_path}")
    endif()
endfunction()

file(REAL_PATH "${SYNTH_BUILD_ROOT}" _build_root)
file(REAL_PATH "${SYNTH_STAGE_DIRECTORY}" _stage_root)
set(_build_manifest_path "${_stage_root}/build-manifest.json")
set(_validation_manifest_path "${_stage_root}/validation-manifest.json")
_synth_read_json(_build_manifest "${_build_manifest_path}" "build manifest")
_synth_read_json(_validation "${_validation_manifest_path}" "validation manifest")

string(JSON _schema GET "${_validation}" schema_version)
if(NOT _schema STREQUAL "1")
    message(FATAL_ERROR "unsupported validation manifest schema: ${_schema}")
endif()
file(SHA256 "${_build_manifest_path}" _actual_build_manifest_sha256)
string(JSON _build_manifest_relative GET "${_validation}" build_manifest path)
string(JSON _declared_build_manifest_sha256 GET "${_validation}" build_manifest sha256)
if(NOT _build_manifest_relative STREQUAL "build-manifest.json"
   OR NOT _declared_build_manifest_sha256 STREQUAL _actual_build_manifest_sha256)
    message(FATAL_ERROR "validation manifest is not linked to the current build manifest")
endif()

string(JSON _repeat_count GET "${_validation}" repeat_count)
string(JSON _seed GET "${_validation}" seed)
if(NOT _repeat_count STREQUAL SYNTH_REPEAT_COUNT OR NOT _seed STREQUAL SYNTH_SEED)
    message(FATAL_ERROR "validation repeat count/seed does not match the configured contract")
endif()

string(JSON _product_count LENGTH "${_build_manifest}" products)
set(_vst3_count 0)
if(_product_count GREATER 0)
    math(EXPR _last_product "${_product_count} - 1")
    foreach(_product_index RANGE 0 ${_last_product})
        string(JSON _format GET "${_build_manifest}" products ${_product_index} format)
        if(_format STREQUAL "VST3")
            math(EXPR _vst3_count "${_vst3_count} + 1")
            string(JSON _final_vst3_relative_path GET "${_build_manifest}" products ${_product_index} relative_path)
            string(JSON _final_vst3_sha256 GET "${_build_manifest}" products ${_product_index} aggregate_sha256)
        endif()
    endforeach()
endif()
if(NOT _vst3_count EQUAL 1)
    message(FATAL_ERROR "final build manifest must declare exactly one VST3 product")
endif()

# The build and validation manifests must declare the exact same report set,
# and that set must equal the fixed set constructed by the build graph.
set(_build_paths "")
set(_build_hashes "")
string(JSON _build_report_count LENGTH "${_build_manifest}" test_reports)
if(_build_report_count GREATER 0)
    math(EXPR _last_build_report "${_build_report_count} - 1")
    foreach(_index RANGE 0 ${_last_build_report})
        string(JSON _path GET "${_build_manifest}" test_reports ${_index} path)
        string(JSON _sha256 GET "${_build_manifest}" test_reports ${_index} sha256)
        list(FIND _build_paths "${_path}" _duplicate)
        if(NOT _duplicate EQUAL -1)
            message(FATAL_ERROR "build manifest contains duplicate evidence: ${_path}")
        endif()
        _synth_verify_build_evidence("${_path}" "${_sha256}" "build-manifest evidence")
        list(APPEND _build_paths "${_path}")
        list(APPEND _build_hashes "${_sha256}")
    endforeach()
endif()
set(_validation_paths "")
string(JSON _validation_evidence_count LENGTH "${_validation}" evidence)
if(_validation_evidence_count GREATER 0)
    math(EXPR _last_validation_evidence "${_validation_evidence_count} - 1")
    foreach(_index RANGE 0 ${_last_validation_evidence})
        string(JSON _path GET "${_validation}" evidence ${_index} path)
        string(JSON _sha256 GET "${_validation}" evidence ${_index} sha256)
        list(FIND _validation_paths "${_path}" _duplicate)
        if(NOT _duplicate EQUAL -1)
            message(FATAL_ERROR "validation manifest contains duplicate evidence: ${_path}")
        endif()
        list(FIND _build_paths "${_path}" _build_index)
        if(_build_index EQUAL -1)
            message(FATAL_ERROR "validation manifest contains undeclared evidence: ${_path}")
        endif()
        list(GET _build_hashes ${_build_index} _build_sha256)
        if(NOT _sha256 STREQUAL _build_sha256)
            message(FATAL_ERROR "manifests disagree on evidence hash: ${_path}")
        endif()
        _synth_verify_build_evidence("${_path}" "${_sha256}" "validation evidence")
        list(APPEND _validation_paths "${_path}")
    endforeach()
endif()
set(_expected_paths ${SYNTH_EXPECTED_EVIDENCE})
list(SORT _expected_paths)
list(SORT _build_paths)
list(SORT _validation_paths)
if(NOT _build_paths STREQUAL _expected_paths OR NOT _validation_paths STREQUAL _expected_paths)
    message(FATAL_ERROR "missing or undeclared validation evidence in linked manifests")
endif()

_synth_read_json(_provision_report
    "${_build_root}/validation/pluginval-provision.json" "pluginval provision report")
_synth_read_json(_pluginval_report
    "${_build_root}/validation/pluginval-run-report.json" "pluginval run report")
_synth_read_json(_auval_report
    "${_build_root}/validation/auval-report.json" "auval report")
string(JSON _embedded_provision GET "${_validation}" pluginval provision)
string(JSON _embedded_pluginval GET "${_validation}" pluginval run)
string(JSON _embedded_auval GET "${_validation}" auval)
_synth_require_same_json("${_embedded_provision}" "${_provision_report}"
                         "embedded pluginval provision metadata")
_synth_require_same_json("${_embedded_pluginval}" "${_pluginval_report}"
                         "embedded pluginval run metadata")
_synth_require_same_json("${_embedded_auval}" "${_auval_report}"
                         "embedded auval metadata")

string(JSON _wrapper_status GET "${_validation}" actual_wrapper status)
string(JSON _wrapper_report_path GET "${_validation}" actual_wrapper report_path)
string(JSON _wrapper_report_sha256 GET "${_validation}" actual_wrapper report_sha256)
string(JSON _wrapper_log_path GET "${_validation}" actual_wrapper log_path)
string(JSON _wrapper_log_sha256 GET "${_validation}" actual_wrapper log_sha256)
if(NOT _wrapper_status STREQUAL "pass")
    message(FATAL_ERROR "actual-wrapper aggregate is not pass")
endif()
_synth_verify_build_evidence("${_wrapper_report_path}" "${_wrapper_report_sha256}" "wrapper report")
_synth_verify_build_evidence("${_wrapper_log_path}" "${_wrapper_log_sha256}" "wrapper log")
_synth_read_json(_wrapper_report "${_build_root}/${_wrapper_report_path}" "wrapper report")
string(JSON _wrapper_report_status GET "${_wrapper_report}" status)
string(JSON _wrapper_repeat_count GET "${_wrapper_report}" repeat_count)
string(JSON _wrapper_seed GET "${_wrapper_report}" seed)
string(JSON _wrapper_plugin_path GET "${_wrapper_report}" plugin relative_path)
string(JSON _wrapper_plugin_sha256 GET "${_wrapper_report}" plugin aggregate_sha256)
file(RELATIVE_PATH _stage_relative_from_build "${_build_root}" "${_stage_root}")
string(REPLACE "\\" "/" _stage_relative_from_build "${_stage_relative_from_build}")
set(_expected_wrapper_plugin_path
    "${_stage_relative_from_build}/${_final_vst3_relative_path}")
if(NOT _wrapper_report_status STREQUAL "pass"
   OR NOT _wrapper_repeat_count STREQUAL SYNTH_REPEAT_COUNT
   OR NOT _wrapper_seed STREQUAL SYNTH_SEED
   OR NOT _wrapper_plugin_path STREQUAL _expected_wrapper_plugin_path
   OR NOT _wrapper_plugin_sha256 STREQUAL _final_vst3_sha256)
    message(FATAL_ERROR "wrapper report is inconsistent with validation metadata")
endif()

string(JSON _provision_version GET "${_validation}" pluginval provision version)
string(JSON _provision_version_output GET "${_validation}" pluginval provision version_output)
string(JSON _archive_status GET "${_validation}" pluginval provision archive_status)
string(JSON _archive_sha256 GET "${_validation}" pluginval provision archive_sha256)
string(JSON _expected_archive_sha256 GET "${_validation}" pluginval provision expected_archive_sha256)
string(JSON _executable_sha256 GET "${_validation}" pluginval provision executable_sha256)
_synth_require_status("${_archive_status}" "pluginval archive")
if(NOT _provision_version STREQUAL "1.0.4"
   OR NOT _provision_version_output STREQUAL "pluginval - 1.0.4"
   OR _executable_sha256 STREQUAL "")
    message(FATAL_ERROR "pluginval provisioning provenance is inconsistent")
endif()
if(_archive_status STREQUAL "pass" AND NOT _archive_sha256 STREQUAL _expected_archive_sha256)
    message(FATAL_ERROR "pluginval archive hash is inconsistent")
endif()

string(JSON _pluginval_status GET "${_validation}" pluginval run status)
string(JSON _pluginval_version GET "${_validation}" pluginval run tool_version)
string(JSON _pluginval_repeat_count GET "${_validation}" pluginval run repeat_count)
string(JSON _pluginval_seed GET "${_validation}" pluginval run seed)
string(JSON _pluginval_strictness GET "${_validation}" pluginval run strictness_level)
string(JSON _pluginval_timeout GET "${_validation}" pluginval run timeout_ms)
string(JSON _pluginval_isolated GET "${_validation}" pluginval run isolated_process)
string(JSON _pluginval_gui GET "${_validation}" pluginval run gui_tests)
string(JSON _run_executable_sha256 GET "${_validation}" pluginval run executable_sha256)
string(JSON _pluginval_plugin_path GET "${_validation}" pluginval run plugin_relative_path)
string(JSON _pluginval_plugin_sha256 GET "${_validation}" pluginval run plugin_aggregate_sha256)
if(NOT _pluginval_status STREQUAL "pass"
   OR NOT _pluginval_version STREQUAL "1.0.4"
   OR NOT _pluginval_repeat_count STREQUAL SYNTH_REPEAT_COUNT
   OR NOT _pluginval_seed STREQUAL SYNTH_SEED
   OR NOT _pluginval_strictness STREQUAL "10"
   OR NOT _pluginval_timeout STREQUAL "60000"
   OR NOT _pluginval_isolated
   OR NOT _pluginval_gui
   OR NOT _run_executable_sha256 STREQUAL _executable_sha256
   OR NOT _pluginval_plugin_path STREQUAL _final_vst3_relative_path
   OR NOT _pluginval_plugin_sha256 STREQUAL _final_vst3_sha256)
    message(FATAL_ERROR "pluginval run contract is inconsistent")
endif()
string(JSON _pluginval_repeat_length LENGTH "${_validation}" pluginval run repeats)
if(NOT _pluginval_repeat_length STREQUAL SYNTH_REPEAT_COUNT)
    message(FATAL_ERROR "pluginval did not record the configured number of isolated processes")
endif()
string(JSON _vst3_status GET "${_validation}" vst3_sdk_validator status)
_synth_require_status("${_vst3_status}" "VST3 SDK validator")
math(EXPR _last_pluginval_repeat "${_pluginval_repeat_length} - 1")
foreach(_index RANGE 0 ${_last_pluginval_repeat})
    string(JSON _repeat_status GET "${_validation}" pluginval run repeats ${_index} status)
    string(JSON _report_path GET "${_validation}" pluginval run repeats ${_index} report_path)
    string(JSON _report_sha256 GET "${_validation}" pluginval run repeats ${_index} report_sha256)
    string(JSON _log_path GET "${_validation}" pluginval run repeats ${_index} process_log_path)
    string(JSON _log_sha256 GET "${_validation}" pluginval run repeats ${_index} process_log_sha256)
    if(NOT _repeat_status STREQUAL "pass")
        message(FATAL_ERROR "pluginval repeat ${_index} is not pass")
    endif()
    _synth_verify_build_evidence("${_report_path}" "${_report_sha256}" "pluginval report")
    _synth_verify_build_evidence("${_log_path}" "${_log_sha256}" "pluginval process log")
    math(EXPR _repeat_number "${_index} + 1")
    set(_expected_command "")
    string(JSON _validation_os GET "${_validation}" environment os)
    if(_validation_os STREQUAL "Linux")
        list(APPEND _expected_command xvfb-run -a)
    endif()
    list(APPEND _expected_command
        pluginval
        --validate "${_expected_wrapper_plugin_path}"
        --strictness-level 10
        --random-seed "${SYNTH_SEED}"
        --timeout-ms 60000
        --output-dir "validation/pluginval/repeat-${_repeat_number}"
        --output-filename pluginval-report.txt)
    if(_vst3_status STREQUAL "pass")
        list(APPEND _expected_command --vst3validator configured-vst3-validator)
    endif()
    set(_actual_command "")
    string(JSON _command_length LENGTH "${_validation}" pluginval run repeats ${_index} command)
    if(_command_length GREATER 0)
        math(EXPR _last_command_token "${_command_length} - 1")
        foreach(_command_index RANGE 0 ${_last_command_token})
            string(JSON _command_token GET "${_validation}" pluginval run repeats ${_index} command ${_command_index})
            list(APPEND _actual_command "${_command_token}")
        endforeach()
    endif()
    if(NOT _actual_command STREQUAL _expected_command)
        message(FATAL_ERROR "pluginval repeat ${_repeat_number} exact command/options are inconsistent")
    endif()
    file(READ "${_build_root}/${_log_path}" _process_log)
    foreach(_required_log_line IN ITEMS
            "isolated_process=true"
            "gui_tests=enabled"
            "strictness_level=10"
            "random_seed=${SYNTH_SEED}"
            "timeout_ms=60000")
        if(NOT _process_log MATCHES "${_required_log_line}")
            message(FATAL_ERROR "pluginval process log omits required option: ${_required_log_line}")
        endif()
    endforeach()
    if(_process_log MATCHES "validate-in-process" OR _process_log MATCHES "skip-gui-tests")
        message(FATAL_ERROR "pluginval process log contains a prohibited option")
    endif()
endforeach()

if(_vst3_status STREQUAL "pass")
    string(JSON _vst3_hash GET "${_validation}" vst3_sdk_validator executable_sha256)
    if(_vst3_hash STREQUAL "")
        message(FATAL_ERROR "VST3 SDK validator pass lacks executable provenance")
    endif()
endif()

string(JSON _auval_status GET "${_validation}" auval status)
string(JSON _auval_command GET "${_validation}" auval command)
string(JSON _auval_version GET "${_validation}" auval version)
string(JSON _auval_log_path GET "${_validation}" auval log_path)
string(JSON _auval_log_sha256 GET "${_validation}" auval log_sha256)
_synth_require_status("${_auval_status}" "auval")
if(NOT _auval_command STREQUAL "auval -v aumu ${SYNTH_PRODUCT_CODE} ${SYNTH_MANUFACTURER_CODE}")
    message(FATAL_ERROR "auval command is not the exact required component validation command")
endif()
if(_auval_status STREQUAL "pass" AND _auval_version STREQUAL "")
    message(FATAL_ERROR "auval pass lacks exact version provenance")
endif()
_synth_verify_build_evidence("${_auval_log_path}" "${_auval_log_sha256}" "auval log")

file(SHA256 "${SYNTH_HOST_MATRIX_PATH}" _expected_host_sha256)
_synth_read_json(_host_definition "${SYNTH_HOST_MATRIX_PATH}" "required host definition")
string(JSON _definition_row_count LENGTH "${_host_definition}" rows)
string(JSON _definition_check_count LENGTH "${_host_definition}" checks)
string(JSON _host_sha256 GET "${_validation}" hosts definition_sha256)
string(JSON _host_row_count LENGTH "${_validation}" hosts rows)
if(NOT _host_sha256 STREQUAL _expected_host_sha256
   OR NOT _host_row_count EQUAL 11
   OR NOT _definition_row_count EQUAL 11
   OR NOT _definition_check_count EQUAL 9)
    message(FATAL_ERROR "host matrix definition/hash/row count is inconsistent")
endif()
list(FIND _build_paths "validation/required-host-matrix.json" _host_evidence_index)
if(_host_evidence_index EQUAL -1)
    message(FATAL_ERROR "hashed host matrix is absent from build evidence")
endif()
list(GET _build_hashes ${_host_evidence_index} _host_evidence_sha256)
if(NOT _host_evidence_sha256 STREQUAL _expected_host_sha256)
    message(FATAL_ERROR "build evidence host matrix differs from the hashed source definition")
endif()
math(EXPR _last_host_row "${_host_row_count} - 1")
foreach(_row_index RANGE 0 ${_last_host_row})
    string(JSON _row_status GET "${_validation}" hosts rows ${_row_index} status)
    string(JSON _row_kind GET "${_validation}" hosts rows ${_row_index} kind)
    string(JSON _row_name GET "${_validation}" hosts rows ${_row_index} name)
    string(JSON _row_version GET "${_validation}" hosts rows ${_row_index} required_version)
    string(JSON _row_platform GET "${_validation}" hosts rows ${_row_index} platform)
    string(JSON _row_source GET "${_validation}" hosts rows ${_row_index} source_url)
    string(JSON _expected_name GET "${_host_definition}" rows ${_row_index} name)
    string(JSON _expected_version GET "${_host_definition}" rows ${_row_index} required_version)
    string(JSON _expected_platform GET "${_host_definition}" rows ${_row_index} platform)
    string(JSON _expected_source GET "${_host_definition}" rows ${_row_index} source_url)
    string(JSON _expected_kind GET "${_host_definition}" rows ${_row_index} kind)
    if(_expected_version STREQUAL "\${PROJECT_VERSION}")
        set(_expected_version "${SYNTH_PROJECT_VERSION}")
    endif()
    if(NOT _row_name STREQUAL _expected_name
       OR NOT _row_version STREQUAL _expected_version
       OR NOT _row_platform STREQUAL _expected_platform
       OR NOT _row_source STREQUAL _expected_source
       OR NOT _row_kind STREQUAL _expected_kind)
        message(FATAL_ERROR "host row ${_row_index} does not match its hashed definition")
    endif()
    string(JSON _check_count LENGTH "${_validation}" hosts rows ${_row_index} checks)
    _synth_require_status("${_row_status}" "host row")
    if(NOT _check_count EQUAL 9)
        message(FATAL_ERROR "host row ${_row_index} does not contain all required checks")
    endif()
    if(_row_kind STREQUAL "commercial-host" AND _row_status STREQUAL "pass")
        message(FATAL_ERROR "unexecuted commercial host row cannot be pass")
    endif()
    math(EXPR _last_check "${_check_count} - 1")
    foreach(_check_index RANGE 0 ${_last_check})
        string(JSON _check_status GET "${_validation}" hosts rows ${_row_index} checks ${_check_index} status)
        string(JSON _check_name GET "${_validation}" hosts rows ${_row_index} checks ${_check_index} name)
        string(JSON _expected_check_name GET "${_host_definition}" checks ${_check_index})
        _synth_require_status("${_check_status}" "host check")
        if(NOT _check_name STREQUAL _expected_check_name)
            message(FATAL_ERROR "host row ${_row_index} check ${_check_index} does not match its definition")
        endif()
        if(_check_status STREQUAL "pass")
            message(FATAL_ERROR "unexecuted host check cannot be pass")
        endif()
    endforeach()
endforeach()

string(JSON _identity_approved GET "${_build_manifest}" identity identity_approved)
string(JSON _identity_manufacturer GET "${_build_manifest}" identity manufacturer_name)
string(JSON _identity_domain GET "${_build_manifest}" identity manufacturer_domain)
if(_identity_approved
   AND NOT _identity_manufacturer STREQUAL ""
   AND NOT _identity_manufacturer STREQUAL "yourcompany"
   AND NOT _identity_domain MATCHES "(^|\\.)yourcompany($|\\.)")
    set(_expected_identity_status "pass")
else()
    set(_expected_identity_status "blocked")
endif()
string(JSON _identity_status GET "${_validation}" aggregates identity status)
_synth_require_status("${_identity_status}" "identity aggregate")
if(NOT _identity_status STREQUAL _expected_identity_status)
    message(FATAL_ERROR "identity aggregate is inconsistent with the build manifest identity")
endif()
foreach(_aggregate IN ITEMS validation distribution release)
    string(JSON _aggregate_status GET "${_validation}" aggregates ${_aggregate} status)
    _synth_require_status("${_aggregate_status}" "${_aggregate} aggregate")
    if(NOT _aggregate_status STREQUAL "blocked")
        message(FATAL_ERROR "${_aggregate} aggregate must remain blocked under current gates")
    endif()
endforeach()
message(STATUS "Verified linked validation evidence; release remains blocked")
